#!/usr/bin/env python
import ari_backup

backup = ari_backup.RdiffLVMBackup(
    label='mybackup', source_hostname='localhost',
    remove_older_than_timespec='1M')

backup.add_volume('vg0/root', '/')
backup.include_dir('/etc')
backup.run()
